name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  phar-release:
    name: PHAR
    runs-on: ubuntu-latest

    if: github.repository == 'itsdanielfelix/commusoft-cli'

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Phar for upload
        run: |
          mv builds/commusoft builds/commusoft.phar

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            builds/commusoft.phar
